import Head from 'next/head';
import Image from 'next/image';
import Greeting from '@/components/Greeting/Greeting';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Link from 'next/link';
import { AnimatePresence, motion } from 'framer-motion';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {/* <AnimatePresence>
          <motion.h1
            transition={{ delay: 0.4 }}
            animate={{ fontSize: '5rem' }}
            className={styles.greeting}
            initial={true}
          >
            Hello!
          </motion.h1>
        </AnimatePresence> */}
        <Greeting />
        <Link href="/about">Visit the about page </Link>
      </div>
    </>
  );
}
